### ISSUE TITLE
use nanomsg to communicate

### ISSUE THREAD

**Issue by c-cube** [c-cube/frog-utils#23]
More interesting possibilities of communication.

pattern: each tool has one `Bus` socket on a common `\`Ipc "frog"` address. Interesting events (mainly "job is finished" are broadcasted.)

Opens up the possibility of splitting tools into microservices; e.g., a mail or IRC notifier would be a separate tool (with its own dependencies), and it would listen on the Bus socket for interesting news.

**Comment by Gbury** [comment]
We would most likely need a module that defines a type along with encoders/decoders for the messages passed on this bus. The question would then be where to put that module ? Separate frog-messages lib ? or in frog-utils ?

**Comment by c-cube** [comment]
in frog-utils, like the rest --- using JSON messages with ppx_deriving.
