### ISSUE TITLE
Missing opam dependancy : cairo2

### ISSUE THREAD

**Issue by gburel** [c-cube/frog-utils#26]
Frogutils needs cairo2 as dependancy, because otherwise archimedes is built without and it results in 
ocamlfind: Package `archimedes.cairo' not found

**Comment by Gbury** [comment]
Cairo has two packages on opam (i.e `cairo`and `cairo2`), which interacts strangely with archimedes, but looking at the packages installed on my laptop with frogutils working, it seems that the correct dependency is indeed cairo2.
Closed in b3b9b52a01b94ff3fca23dd116eb878df907e2f2
