### ISSUE TITLE
Froglock/frogmap seems to freeze above at  about 1018 tasks

### ISSUE THREAD

**Issue by Gbury** [c-cube/frog-utils#28]
While running some benchs lately, i have seen that when doing a lot of tests (i.e about 20000), frogmap seems to freeze after doing 1018 tasks, using internal locking (i.e --lock true option, which is the default).
Additionally, when trying to check what happens with ```froglock status```, froglock seemed to be frozen too.

This might be a very problematic issue.

**Comment by Gbury** [comment]
Seems that not using the shiny ```--lock=true```, and instead doing something like ```frogmap --lock=false -- 'froglock cmd'``` solves the problem, so I think the cause is that file descriptors opened by frogmap are not cleaned/closed soon enough and the ```frogmap``` call reaches the file descriptors limit (which can be seen with ```ulimit -{S,H}n```).
So while there is a temporary fix, it might be nice to see how we could clean ```frogmap```'s sub processes file descriptors in time.

**Comment by c-cube** [comment]
I don't remember, but I thought most of IOs were made through `with_foo` functions…

**Comment by Gbury** [comment]
Closed with afc19e9e6220799dc73da632faabe35699f016be
